### ISSUE TITLE
Settlement Duration

### ISSUE THREAD

**Issue by Janey75** [FuelLabs/fuel-bridge#200]
The Sepolia-Fuel bridge takes the same time to settle as Fuel-Sepolia. The depreciated testnet has an 'almost instant' settlement for EVM-Fuel and 6hours for Fuel-EVM. Maybe because the bridge is new but would advise the current settlement time for Sepolia-Fuel should be reduced.

**Comment by DefiCake** [comment]
Hi @Janey75 

As we move on with developments some security parameters are expected to be raised. One of such parameters is the time to reflect deposits made in Sepolia in your Fuel wallet. Originally it was just a couple of blocks on Ethereum, but as Ethereum itself changes, we have to adapt to it and at the moment the finalization time could be from minutes to 24 hours, depending on Ethereum 's finality.

Let me know if I misunderstood anything of your inquiry. Otherwise I 'll be closing the issue soon.

**Comment by DefiCake** [comment]
Feel free to open again, appreciate your interest!
