### ISSUE TITLE
NFT bridging support

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-bridge#31]

**Comment by DefiCake** [comment]
|                        | Pros                                                                                                                                                                                 | Cons                                                                                                                                                                                                                                                                                                                          | Tradeoffs                                                                                                                                                                                                                                |   |
|------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|
| Single contract        | - Reduced integration complexity (indexing, loss of funds due to human factor...)<br>- Easier to apply L1 gas savings<br>- Current trend in pooling (singleton)                      | - Can be expanded to new standards, but migrating to a per-standard approach (bundles of standards)<br>- Increased code complexity; shared risk<br>- Worst parallelization capabilities                                                                                                                                       | - Easier to integrate at the cost of shared risks - one vulnerability could drain all funds<br>- More expensive in L2, less expensive in L1                                                                                              |   |
| Per standard contracts | - Less complexity than single contract<br>- Still easy enough to integrate<br>- Can expand to new standards<br>- Shouldn't be hard to attain the same gas savings as Single Contract | - Since the main use cases are related to fungible tokens, it wouldn't be too different from Single Contract 's cons.<br><br>- NFTs would benefit the most from parallelization, as they wouldn't have to share space with more abundant and liquid ERC20s                                                                    | - Shares most of the pros and cons of Single Contract<br>- Compartimentalize risks between standards at the cost of a slight increase in integration complexity (different entrypoints for different standards vs one single entrypoint) |   |
| Per token contract     | - Reduces shared risks to a minimum, each L1-L2 pair holds its own liquidity<br>- Highest parallelization in L2                                                                      | - Highest complexity, probably needs a router or factory<br>- Would probably need some sort of deterministic deployment system to link L1 and L2 artifacts<br>- Although risk are not shared, implementations would probably still share the same code - so vulnerabilities apply<br>- Most expensive to deploy and use in L1 | - Trades L1 increased complexity and costs for L2 costs                                                                                                                                                                                  |   |

We should additionally consider if the relation `ContractID <-> AssetID <-> SubID` will be hosted offchain or onchain. Hosting onchain would be a case in the border of using blockchain as a database which I usually oppose, but it could tighten the relationship between the L1 and L2 entities, reducing risks of loss of funds (less moving parts, user does not have to input external parameters)

**Comment by DefiCake** [comment]
Just for the record, our last agreement on how to tackle this is:

- We are going to have a L1 contract per standard (one L1 contract will hold ERC20s, another one ERC721, another one ERC1155)
- We are going to have a L2 contract per token (one for USDT, another for DAI, another for BAYC...)

The reasoning being:
- Having single contracts to interact with standards in L1 allow to increase security by not sharing code and interactions with other standards. At the same time, it allows to mine efficient addresses that save on gas
- Having a contract per token on L2 allows to leverage parallelisation in L2.
