### ISSUE TITLE
Training Wheels

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-bridge#58]
Goal: We'd like to be able to deploy future testnet releases to mainnet, while doing everything we can to minimize any potential loss of funds for users due to upgrades, bugs, or other potential issues. This effort would be considered as adding "training wheels" to the bridge that could be removed once the network is stabilized and sufficiently tested.

High level solution:
Value cap the bridge such that users can only bring de minimis amounts of mainnet assets in the early stages. This will make it clear to users that the network is not stabilized yet, and in the case where funds cannot be easily recovered there would be no significant impacts. This could entail whitelisting which tokens are bridgeable, and placing a limit on each kind of asset based on an estimated fair market value. In addition to a global value restriction, there could also be account level restrictions to ensure each user is protected.

**Comment by Voxelot** [comment]
cc @Braqzen @DefiCake @luizstacio @K1-R1 @Salka1988

**Comment by K1-R1** [comment]
The solution of account level value restrictions and asset whitelisting seems very reasonable to me. As previously mentioned the global cap alone could be abused, even with additional account-level caps. 
Perhaps a naive question, but if we're looking at a sort of Kusama-style chain; as long as we have snapshots of the state of the chain; in the event that anything goes significantly wrong could we just implement a fix and re-initialise starting at a prior safe state? 
Obviously not acceptable for the full mainnet, but would allow for funds to be recovered from a restricted-mainnet

**Comment by Braqzen** [comment]
Initial thoughts:

1. Global cap on its own is easily abuseable by a small number of participants and it limits overall participation. You do not want to cap your userbase because that kills your product.
2. Account caps can be circumvented with multiple accounts and it's a pain to deal with fluctuating market value.
3. Whitelist must be maintained which is a logistical problem for allowing people to come into the ecosystem.
4. Snapshots are nice but may be resource intensive.

I'm generally against all forms of intervention. It's against the ethos of crypto.
I'd prefer a clear and concise warning to let people know that it's a pre-mainnet unstable testnet with no fallback so if something goes wrong they may lose all funds.
In this case they have to choose to be responsible and use small amounts.

I think this with a snapshot per X number of blocks is the most reasonable depending on the work required to take a snapshot. This way they lose activity from a certain block as a worst case.

**Comment by DefiCake** [comment]
Snapshots are not the silver bullet. As soon as the bug has some outreach to L1, the loss of funds is final - e.g. let's say that there is a theft originated in L2, if the thief manages to withdraw the funds, then no snapshot will protect you: the tokens are already out in somebody else 's pocket.

Protections are already in place, sort of. The contracts are upgradable and pausable. We may want to increase time to finalization, if I am not mistaken it is 3 hours now, so that it gives more room to take measures. If I were to put caps, I 'd resort to do it per account and not globally. It conveys the message in a very clear way, without limiting participation (if you are really that eager to play with your money, be my guest). Although we 'd need to maintain some sort of accounting between L1 and L2.
