### ISSUE TITLE
withdraw from fuel

### ISSUE THREAD

**Issue by MoCrypto11** [FuelLabs/fuel-bridge#94]
there is a problem when trying to withdraw from fuel portal bridge ,the first step which is submit to bridge keeps loading for hours and then nothing .

**Comment by MarcinDegan** [comment]
I have the latest version of the wallet installed, but unfortunately, when I try to view the transaction history on the website, nothing appears. Has the team encountered such issues before? I'd like to add that I'm using the Chrome browser.

**Comment by aaden001** [comment]
same issue with withdraw, any luck?

I get Failed to relay message (transaction reverted)
Need transaction hash

**Comment by MFH015** [comment]
Depois de conectar a carteira metamask, não aparece o botao de confirmar transação, e sim, se mantém o botão de conectar carteira,   aí não é possível realizar as transações

**Comment by Voxelot** [comment]
Is this when trying to withdraw SepoliaETH or ERC-20's?

We're aware that beta-4 has ongoing SepoliaETH liquidity issues due to the faucet, which we've addressed in the upcoming beta-5 release. All other assets types should bridge without any liquidity issues in beta-4. If you encounter any bridging issues on other asset types please let us know.

We appreciate your interest in using Fuel!

**Comment by DefiCake** [comment]
Closing this as it looks stale and we are moving to testnet
